name: release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo' # タイムゾーン指定
        run: echo "CURRENT_DATETIME=$(date +'%Y/%m/%d %H:%M:%S')" >> $GITHUB_ENV
  
      - run: |
          cd ./mods
          zip mods.zip ./*.jar
          
      - uses: actions/create-release@master
        id: create_release # ファイルアップロードに outputs の値を使用するため ID が必要
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.CURRENT_DATETIME }}
          
      - uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # リリースのアップロード URL (必須)
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # 添付ファイルのパス (必須)
          asset_path: ./mods.zip
          # 添付ファイルの表示名 (必須)
          asset_name: mods.zip
          # 添付ファイルに対応する content-type (必須)
          asset_content_type: application/zip
